import { buildTemplateFamily } from '../defaults'

export const templateFamilies = {
  'classic-single-column': buildTemplateFamily({
    id: 'classic-single-column',
    editor: {
      allowedSkeletons: ['single-column', 'stacked'],
      allowedHeaderVariants: ['default', 'compact'],
      allowedDensity: ['compact', 'normal', 'comfortable'],
      allowedTokenPresets: {
        color: ['default', 'modern'],
        font: ['default'],
        spacing: ['default', 'compact'],
        radius: ['none', 'sm'],
      },
      sectionPalette: ['job_intent', 'application_info', 'education', 'work_experience', 'internship_experience', 'campus_experience', 'project_experience', 'skills', 'honors_certificates', 'self_evaluation', 'hobbies'],
      sectionVariants: {
        basics: ['default', 'compact'],
        job_intent: ['default', 'compact'],
        application_info: ['default'],
        education: ['default'],
        work_experience: ['default'],
        internship_experience: ['default'],
        campus_experience: ['default'],
        project_experience: ['default'],
        skills: ['default', 'badge'],
        honors_certificates: ['default'],
        self_evaluation: ['default'],
        hobbies: ['default'],
      },
    },
  }),
  'modern-sidebar-left': buildTemplateFamily({
    id: 'modern-sidebar-left',
    defaultLayout: {
      skeleton: 'sidebar-left',
      headerVariant: 'split',
      density: 'normal',
      page: {
        size: 'A4',
        pagePaddingToken: 'md',
      },
    },
    defaultTokens: {
      colorPreset: 'modern',
      fontPreset: 'default',
      spacingPreset: 'default',
      radiusPreset: 'sm',
    },
    editor: {
      allowedSkeletons: ['sidebar-left', 'sidebar-right', 'single-column'],
      allowedHeaderVariants: ['split', 'default'],
      allowedDensity: ['normal', 'comfortable'],
      allowedTokenPresets: {
        color: ['default', 'modern'],
        font: ['default'],
        spacing: ['default', 'compact'],
        radius: ['none', 'sm'],
      },
      sectionPalette: ['job_intent', 'application_info', 'education', 'work_experience', 'internship_experience', 'campus_experience', 'project_experience', 'skills', 'honors_certificates', 'self_evaluation', 'hobbies'],
      sectionVariants: {
        basics: ['split', 'default'],
        job_intent: ['compact', 'default'],
        application_info: ['default'],
        education: ['timeline', 'default'],
        work_experience: ['timeline', 'default'],
        internship_experience: ['default'],
        campus_experience: ['default'],
        project_experience: ['timeline', 'default'],
        skills: ['badge', 'default'],
        honors_certificates: ['default'],
        self_evaluation: ['highlight', 'default'],
        hobbies: ['default'],
      },
    },
  }),
  'modern-sidebar-right': buildTemplateFamily({
    id: 'modern-sidebar-right',
    defaultLayout: {
      skeleton: 'sidebar-right',
      headerVariant: 'split',
      density: 'normal',
      page: {
        size: 'A4',
        pagePaddingToken: 'md',
      },
    },
    defaultTokens: {
      colorPreset: 'modern',
      fontPreset: 'default',
      spacingPreset: 'default',
      radiusPreset: 'sm',
    },
    editor: {
      allowedSkeletons: ['sidebar-right', 'sidebar-left', 'single-column'],
      allowedHeaderVariants: ['split', 'default'],
      allowedDensity: ['normal', 'comfortable'],
      allowedTokenPresets: {
        color: ['default', 'modern'],
        font: ['default'],
        spacing: ['default', 'compact'],
        radius: ['none', 'sm'],
      },
      sectionPalette: ['job_intent', 'application_info', 'education', 'work_experience', 'internship_experience', 'campus_experience', 'project_experience', 'skills', 'honors_certificates', 'self_evaluation', 'hobbies'],
      sectionVariants: {
        basics: ['split', 'default'],
        job_intent: ['compact', 'default'],
        application_info: ['default'],
        education: ['timeline', 'default'],
        work_experience: ['timeline', 'default'],
        internship_experience: ['default'],
        campus_experience: ['default'],
        project_experience: ['timeline', 'default'],
        skills: ['badge', 'default'],
        honors_certificates: ['default'],
        self_evaluation: ['highlight', 'default'],
        hobbies: ['default'],
      },
    },
  }),
  'ats-compact': buildTemplateFamily({
    id: 'ats-compact',
    defaultLayout: {
      skeleton: 'single-column',
      headerVariant: 'compact',
      density: 'compact',
      page: {
        size: 'A4',
        pagePaddingToken: 'sm',
      },
    },
    defaultTokens: {
      colorPreset: 'default',
      fontPreset: 'default',
      spacingPreset: 'compact',
      radiusPreset: 'none',
    },
    editor: {
      allowedSkeletons: ['single-column'],
      allowedHeaderVariants: ['compact', 'default'],
      allowedDensity: ['compact', 'normal'],
      allowedTokenPresets: {
        color: ['default'],
        font: ['default'],
        spacing: ['compact', 'default'],
        radius: ['none'],
      },
      sectionPalette: ['job_intent', 'application_info', 'education', 'work_experience', 'internship_experience', 'campus_experience', 'project_experience', 'skills', 'honors_certificates', 'self_evaluation', 'hobbies'],
      sectionVariants: {
        basics: ['compact', 'default'],
        job_intent: ['compact'],
        application_info: ['default'],
        education: ['default'],
        work_experience: ['default'],
        internship_experience: ['default'],
        campus_experience: ['default'],
        project_experience: ['default'],
        skills: ['compact', 'default'],
        honors_certificates: ['default'],
        self_evaluation: ['default'],
        hobbies: ['default'],
      },
    },
  }),
  'showcase-stacked': buildTemplateFamily({
    id: 'showcase-stacked',
    defaultLayout: {
      skeleton: 'stacked',
      headerVariant: 'split',
      density: 'comfortable',
      page: {
        size: 'A4',
        pagePaddingToken: 'lg',
      },
    },
    defaultTokens: {
      colorPreset: 'modern',
      fontPreset: 'default',
      spacingPreset: 'default',
      radiusPreset: 'sm',
    },
    editor: {
      allowedSkeletons: ['stacked', 'single-column'],
      allowedHeaderVariants: ['split', 'default', 'compact'],
      allowedDensity: ['normal', 'comfortable'],
      allowedTokenPresets: {
        color: ['default', 'modern'],
        font: ['default'],
        spacing: ['default', 'compact'],
        radius: ['none', 'sm'],
      },
      sectionPalette: ['job_intent', 'application_info', 'education', 'work_experience', 'internship_experience', 'campus_experience', 'project_experience', 'skills', 'honors_certificates', 'self_evaluation', 'hobbies'],
      sectionVariants: {
        basics: ['split', 'default'],
        job_intent: ['default', 'compact'],
        application_info: ['default'],
        education: ['timeline', 'default'],
        work_experience: ['timeline', 'default'],
        internship_experience: ['default'],
        campus_experience: ['default'],
        project_experience: ['timeline', 'default'],
        skills: ['badge', 'default'],
        honors_certificates: ['default'],
        self_evaluation: ['highlight', 'default'],
        hobbies: ['default'],
      },
    },
  }),
} as const

export type TemplateFamilyId = keyof typeof templateFamilies
