import type { JobApplication } from './types'

export const mockApplications: JobApplication[] = [
  {
    id: '1',
    created_at: new Date().toISOString(),
    resume_id: null,
    user_id: 'mock-user',
    company: 'Google',
    company_logo: 'https://www.google.com/favicon.ico',
    position: 'Software Engineer',
    location: 'San Francisco',
    salary: '$150k - $200k',
    job_url: 'https://google.com/careers',
    status: 'interview',
    stage_details: [
      { stage: 'saved', status: '已完成', start_date: '2024-01-25', notes: '' },
      { stage: 'applied', status: '已完成', start_date: '2024-01-26', notes: '' },
      { stage: 'interview', status: '进行中', start_date: '2024-01-28', notes: '' },
    ],
    applied_date: '2024-01-26',
    notes: null,
  },
  {
    id: '2',
    created_at: new Date().toISOString(),
    resume_id: null,
    user_id: 'mock-user',
    company: 'Microsoft',
    company_logo: 'https://www.microsoft.com/favicon.ico',
    position: 'Frontend Developer',
    location: 'Seattle',
    salary: '$140k - $180k',
    job_url: 'https://microsoft.com/careers',
    status: 'applied',
    stage_details: [
      { stage: 'saved', status: '已完成', start_date: '2024-01-20', notes: '' },
      { stage: 'applied', status: '进行中', start_date: '2024-01-22', notes: '' },
    ],
    applied_date: '2024-01-22',
    notes: null,
  },
  {
    id: '3',
    created_at: new Date().toISOString(),
    resume_id: null,
    user_id: 'mock-user',
    company: 'Apple',
    company_logo: 'https://www.apple.com/favicon.ico',
    position: 'iOS Developer',
    location: 'Cupertino',
    salary: '$160k - $220k',
    job_url: null,
    status: 'saved',
    stage_details: [
      { stage: 'saved', status: '待处理', start_date: null, notes: '' },
    ],
    applied_date: null,
    notes: null,
  },
]
