create table public.resume_config (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id uuid not null default auth.uid (),
  type text null default 'default'::text,
  basics jsonb null,
  job_intent jsonb null,
  application_info jsonb null,
  edu_background jsonb null,
  work_experience jsonb null,
  internship_experience jsonb null,
  campus_experience jsonb null,
  project_experience jsonb null,
  skill_specialty jsonb null,
  honors_certificates jsonb null,
  self_evaluation jsonb null,
  hobbies jsonb null,
  "order" jsonb null default '["basics", "jobIntent", "applicationInfo", "eduBackground", "workExperience", "internshipExperience", "campusExperience", "projectExperience", "skillSpecialty", "honorsCertificates", "selfEvaluation", "hobbies"]'::jsonb,
  visibility jsonb null,
  updated_at timestamp with time zone null default now(),
  display_name text null default '简历'::text,
  description text null,
  resume_id uuid not null default gen_random_uuid (),
  automerge_enabled boolean null default true,
  document_version integer null default 1,
  constraint resume_config_pkey primary key (id),
  constraint resume_config_resume_id_key unique (resume_id),
  constraint resume_config_resume_id_fkey foreign KEY (user_id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_resume_config_automerge on public.resume_config using btree (automerge_enabled) TABLESPACE pg_default
where
  (automerge_enabled = true);

create trigger resume_config_updated
after INSERT
or DELETE
or
update on resume_config for EACH row
execute FUNCTION update_updated_at_column ();

create trigger update_resume_config_updated_at BEFORE
update on resume_config for EACH row
execute FUNCTION update_updated_at_column ();
