create table public.resume_config_versions (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  user_id uuid not null default auth.uid(),
  resume_id uuid not null,
  version_no integer not null,
  version_name text null,
  description text null,
  milestone_name text null,
  source_type text not null default 'manual'::text,
  tags jsonb null default '[]'::jsonb,
  snapshot jsonb not null,
  content_hash text null,
  base_updated_at timestamp with time zone null,
  constraint resume_config_versions_pkey primary key (id),
  constraint resume_config_versions_resume_id_fkey
    foreign key (resume_id)
    references public.resume_config (resume_id)
    on delete cascade,
  constraint resume_config_versions_user_id_fkey
    foreign key (user_id)
    references auth.users (id)
    on delete cascade,
  constraint resume_config_versions_resume_id_version_no_key
    unique (resume_id, version_no),
  constraint resume_config_versions_source_type_check
    check (
      source_type in (
        'manual',
        'autosave',
        'restore',
        'ai_optimize',
        'import'
      )
    ),
  constraint resume_config_versions_tags_is_array_check
    check (
      tags is null
      or jsonb_typeof(tags) = 'array'
    ),
  constraint resume_config_versions_snapshot_is_object_check
    check (
      jsonb_typeof(snapshot) = 'object'
    )
) tablespace pg_default;

create or replace function public.set_resume_config_version_no()
returns trigger
language plpgsql
as $$
declare
  next_version_no integer;
begin
  select coalesce(max(version_no), 0) + 1
  into next_version_no
  from public.resume_config_versions
  where resume_id = new.resume_id;

  new.version_no := next_version_no;
  return new;
end;
$$;

create trigger set_resume_config_version_no_trigger
before insert on public.resume_config_versions
for each row
execute function public.set_resume_config_version_no();

create trigger update_resume_config_versions_updated_at
before update on public.resume_config_versions
for each row
execute function update_updated_at_column();

create index if not exists idx_resume_config_versions_resume_id
on public.resume_config_versions using btree (resume_id) tablespace pg_default;

create index if not exists idx_resume_config_versions_user_id
on public.resume_config_versions using btree (user_id) tablespace pg_default;

create index if not exists idx_resume_config_versions_resume_id_created_at
on public.resume_config_versions using btree (resume_id, created_at desc) tablespace pg_default;

create index if not exists idx_resume_config_versions_resume_id_version_no_desc
on public.resume_config_versions using btree (resume_id, version_no desc) tablespace pg_default;

create index if not exists idx_resume_config_versions_resume_id_milestone_name
on public.resume_config_versions using btree (resume_id, milestone_name) tablespace pg_default
where milestone_name is not null;

create index if not exists idx_resume_config_versions_content_hash
on public.resume_config_versions using btree (resume_id, content_hash) tablespace pg_default
where content_hash is not null;
