create table public.ats (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  resume_id uuid not null,
  user_id uuid null default auth.uid (),
  version text null,
  meta jsonb null,
  "readabilityIndex" jsonb null,
  "fixChecklist" jsonb[] null,
  summary jsonb null,
  scores jsonb null,
  findings jsonb null,
  todo_items jsonb[] null default '{}'::jsonb[],
  constraint ats_pkey primary key (id),
  constraint ats_resume_id_fkey foreign KEY (resume_id) references resume_config (resume_id) on update CASCADE on delete CASCADE,
  constraint ats_user_id_fkey foreign KEY (user_id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;
