create table public.resume_templates (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  template_id uuid not null default gen_random_uuid(),
  user_id uuid not null default auth.uid(),
  family_id text not null,
  based_on_template_id text null,
  name text not null,
  description text null,
  visibility text not null default 'private'::text,
  status text not null default 'active'::text,
  manifest jsonb not null,
  constraint resume_templates_pkey primary key (id),
  constraint resume_templates_template_id_key unique (template_id),
  constraint resume_templates_user_id_fkey
    foreign key (user_id)
    references auth.users (id)
    on delete cascade,
  constraint resume_templates_visibility_check
    check (visibility in ('private', 'published')),
  constraint resume_templates_status_check
    check (status in ('draft', 'active', 'archived')),
  constraint resume_templates_manifest_is_object_check
    check (jsonb_typeof(manifest) = 'object')
) tablespace pg_default;

create index if not exists idx_resume_templates_user_id
on public.resume_templates using btree (user_id) tablespace pg_default;

create index if not exists idx_resume_templates_user_id_updated_at_desc
on public.resume_templates using btree (user_id, updated_at desc) tablespace pg_default;

create index if not exists idx_resume_templates_user_id_visibility
on public.resume_templates using btree (user_id, visibility) tablespace pg_default;

create trigger update_resume_templates_updated_at
before update on public.resume_templates
for each row
execute function update_updated_at_column();
