create table public.ats (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  resume_id uuid not null,
  user_id uuid null default auth.uid (),
  version text null,
  meta jsonb null,
  "readabilityIndex" jsonb null,
  "fixChecklist" jsonb[] null,
  summary jsonb null,
  scores jsonb null,
  findings jsonb null,
  todo_items jsonb[] null default '{}'::jsonb[],
  constraint ats_pkey primary key (id),
  constraint ats_resume_id_fkey foreign KEY (resume_id) references resume_config (resume_id) on update CASCADE on delete CASCADE,
  constraint ats_user_id_fkey foreign KEY (user_id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;

create table public.ats (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  resume_id uuid not null,
  user_id uuid null default auth.uid (),
  version text null,
  meta jsonb null,
  "readabilityIndex" jsonb null,
  "fixChecklist" jsonb[] null,
  summary jsonb null,
  scores jsonb null,
  findings jsonb null,
  todo_items jsonb[] null default '{}'::jsonb[],
  constraint ats_pkey primary key (id),
  constraint ats_resume_id_fkey foreign KEY (resume_id) references resume_config (resume_id) on update CASCADE on delete CASCADE,
  constraint ats_user_id_fkey foreign KEY (user_id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;

create table public.company (
  id uuid not null default gen_random_uuid (),
  created_at timestamp with time zone null default now(),
  updated_at timestamp with time zone null default now(),
  user_id uuid not null,
  resume_id uuid null,
  company text not null,
  company_logo text null,
  position text not null,
  location text not null,
  salary text null,
  job_url text null,
  status text not null default 'saved'::text,
  stage_details jsonb not null default '[]'::jsonb,
  interview_sub_stages jsonb null default '[]'::jsonb,
  constraint company_pkey primary key (id),
  constraint company_resume_id_fkey foreign KEY (resume_id) references resume_config (resume_id) on delete set null,
  constraint company_user_id_fkey foreign KEY (user_id) references auth.users (id) on delete CASCADE,
  constraint company_status_check check (
    (
      status = any (
        array[
          'saved'::text,
          'applied'::text,
          'screen'::text,
          'interview'::text,
          'offer'::text,
          'rejected'::text
        ]
      )
    )
  )
) TABLESPACE pg_default;

create table public.resume_config (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  user_id uuid not null default auth.uid (),
  type text null default 'default'::text,
  basics jsonb null,
  job_intent jsonb null,
  application_info jsonb null,
  edu_background jsonb null,
  work_experience jsonb null,
  internship_experience jsonb null,
  campus_experience jsonb null,
  project_experience jsonb null,
  skill_specialty jsonb null,
  honors_certificates jsonb null,
  self_evaluation jsonb null,
  hobbies jsonb null,
  "order" jsonb null default '["basics", "jobIntent", "applicationInfo", "eduBackground", "workExperience", "internshipExperience", "campusExperience", "projectExperience", "skillSpecialty", "honorsCertificates", "selfEvaluation", "hobbies"]'::jsonb,
  visibility jsonb null,
  updated_at timestamp with time zone null default now(),
  display_name text null default '简历'::text,
  description text null,
  resume_id uuid not null default gen_random_uuid (),
  automerge_enabled boolean null default true,
  document_version integer null default 1,
  spacing jsonb not null default '{"lineHeight": 1.6, "pageMargin": 16, "sectionSpacing": 20}'::jsonb,
  font jsonb not null default '{"fontSize": 14, "fontFamily": "system"}'::jsonb,
  theme jsonb not null default '{"theme": "default"}'::jsonb,
  template_binding jsonb null,
  constraint resume_config_pkey primary key (id),
  constraint resume_config_resume_id_key unique (resume_id),
  constraint resume_config_resume_id_fkey foreign KEY (user_id) references auth.users (id) on delete CASCADE,
  constraint resume_config_template_binding_is_object_check check (
    (
      (template_binding is null)
      or (jsonb_typeof(template_binding) = 'object'::text)
    )
  )
) TABLESPACE pg_default;

create index IF not exists idx_resume_config_automerge on public.resume_config using btree (automerge_enabled) TABLESPACE pg_default
where
  (automerge_enabled = true);

create trigger resume_config_updated
after INSERT
or DELETE
or
update on resume_config for EACH row
execute FUNCTION update_updated_at_column ();

create trigger update_resume_config_updated_at BEFORE
update on resume_config for EACH row
execute FUNCTION update_updated_at_column ();

create table public.resume_config_versions (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  user_id uuid not null default auth.uid (),
  resume_id uuid not null,
  version_no integer not null,
  version_name text null,
  description text null,
  milestone_name text null,
  source_type text not null default 'manual'::text,
  tags jsonb null default '[]'::jsonb,
  snapshot jsonb not null,
  content_hash text null,
  base_updated_at timestamp with time zone null,
  constraint resume_config_versions_pkey primary key (id),
  constraint resume_config_versions_resume_id_version_no_key unique (resume_id, version_no),
  constraint resume_config_versions_resume_id_fkey foreign KEY (resume_id) references resume_config (resume_id) on delete CASCADE,
  constraint resume_config_versions_user_id_fkey foreign KEY (user_id) references auth.users (id) on delete CASCADE,
  constraint resume_config_versions_snapshot_is_object_check check ((jsonb_typeof(snapshot) = 'object'::text)),
  constraint resume_config_versions_source_type_check check (
    (
      source_type = any (
        array[
          'manual'::text,
          'autosave'::text,
          'restore'::text,
          'ai_optimize'::text,
          'import'::text
        ]
      )
    )
  ),
  constraint resume_config_versions_tags_is_array_check check (
    (
      (tags is null)
      or (jsonb_typeof(tags) = 'array'::text)
    )
  )
) TABLESPACE pg_default;

create index IF not exists idx_resume_config_versions_resume_id on public.resume_config_versions using btree (resume_id) TABLESPACE pg_default;

create index IF not exists idx_resume_config_versions_user_id on public.resume_config_versions using btree (user_id) TABLESPACE pg_default;

create index IF not exists idx_resume_config_versions_resume_id_created_at on public.resume_config_versions using btree (resume_id, created_at desc) TABLESPACE pg_default;

create index IF not exists idx_resume_config_versions_resume_id_version_no_desc on public.resume_config_versions using btree (resume_id, version_no desc) TABLESPACE pg_default;

create index IF not exists idx_resume_config_versions_resume_id_milestone_name on public.resume_config_versions using btree (resume_id, milestone_name) TABLESPACE pg_default
where
  (milestone_name is not null);

create index IF not exists idx_resume_config_versions_content_hash on public.resume_config_versions using btree (resume_id, content_hash) TABLESPACE pg_default
where
  (content_hash is not null);

create trigger set_resume_config_version_no_trigger BEFORE INSERT on resume_config_versions for EACH row
execute FUNCTION set_resume_config_version_no ();

create trigger update_resume_config_versions_updated_at BEFORE
update on resume_config_versions for EACH row
execute FUNCTION update_updated_at_column ();

create table public.resume_templates (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  template_id uuid not null default gen_random_uuid (),
  user_id uuid not null default auth.uid (),
  family_id text not null,
  based_on_template_id text null,
  name text not null,
  description text null,
  visibility text not null default 'private'::text,
  status text not null default 'active'::text,
  manifest jsonb not null,
  constraint resume_templates_pkey primary key (id),
  constraint resume_templates_template_id_key unique (template_id),
  constraint resume_templates_user_id_fkey foreign KEY (user_id) references auth.users (id) on delete CASCADE,
  constraint resume_templates_manifest_is_object_check check ((jsonb_typeof(manifest) = 'object'::text)),
  constraint resume_templates_status_check check (
    (
      status = any (
        array['draft'::text, 'active'::text, 'archived'::text]
      )
    )
  ),
  constraint resume_templates_visibility_check check (
    (
      visibility = any (array['private'::text, 'published'::text])
    )
  )
) TABLESPACE pg_default;

create index IF not exists idx_resume_templates_user_id on public.resume_templates using btree (user_id) TABLESPACE pg_default;

create index IF not exists idx_resume_templates_user_id_updated_at_desc on public.resume_templates using btree (user_id, updated_at desc) TABLESPACE pg_default;

create index IF not exists idx_resume_templates_user_id_visibility on public.resume_templates using btree (user_id, visibility) TABLESPACE pg_default;

create trigger update_resume_templates_updated_at BEFORE
update on resume_templates for EACH row
execute FUNCTION update_updated_at_column ();
